import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
// import Header from "./components/Header";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  // weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Essential Oil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased`}>
      {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}